### ISSUE TITLE
OSError [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by ghost** [patelkelvin/Python-BOT#1]
Do you get an error saying can't find model 'en'. It doesn't seem to be a shortcut link, a python package or a valid path to a data directory?

**Comment by patelkelvin** [comment]
can you describe about error? At which line of code you got error?

**Comment by ghost** [comment]
It's an attribute error, module 'numpy.core.multiarray' has no attribute
_set_madvise_hugepage

**Comment by patelkelvin** [comment]
can you installed Dependencies describe in README.md file?

**Comment by ghost** [comment]
I have all dependencies installed. I have Flask 1.1.2 ChatterBot 1.0.8
chatterbot-corpus 1.2.0 SQL Alchemy 1.3.19

**Comment by patelkelvin** [comment]
can you give version of python?

**Comment by ghost** [comment]
3.7.8

**Comment by ghost** [comment]
What version did you use?

**Comment by patelkelvin** [comment]
and also check is python IDLE is 32 bit or 64 bit?

**Comment by patelkelvin** [comment]
Python 3.7 64 bit

**Comment by patelkelvin** [comment]
because it will not work in 32 bit Python IDLE

**Comment by ghost** [comment]
I'm running 64 bit

**Comment by patelkelvin** [comment]
could you provide screenshot of error?

**Comment by ghost** [comment]
I just sent you a screenshot

**Comment by patelkelvin** [comment]
Please try this codes in command line to install en explicitly 
pip install spacy
python -m spacy download en
python -m spacy link en_core_web_sm en
if error not solved then feel free to comment

**Comment by ghost** [comment]
Nothing

**Comment by ghost** [comment]
What's your github account?

**Comment by ghost** [comment]
You can close this ticket. The issue is fixed. I reinstalled everything,
the Ubuntu  OS, python and the rest of the modules.
